substitutions:
  # Header a ikony
  header_bg_color: 0x000000
  header_border_color: 0x333333
  header_time_color: 0xFFFFFF
  header_date_color: 0xCCCCCC
  accent_blue: 0x2196F3
  icon_color_on: 0x4CAF50
  icon_color_off: 0xAAAAAA

  # Defaultní hodnoty nastavení
  default_deep_sleep_timeout: "900" # 15 minut
  default_ble_scan_interval: "5" # 10 sekund - lepší pro aktualizace
  default_display_brightness: "80" # 80%
  default_display_refresh_interval: "10" # 10 sekunda

# Perzistentní globální proměnné
globals:
  - id: deep_sleep_timeout
    type: int
    restore_value: true
    initial_value: ${default_deep_sleep_timeout}

  - id: ble_scan_interval
    type: int
    restore_value: true
    initial_value: ${default_ble_scan_interval}

  - id: display_brightness
    type: int
    restore_value: true
    initial_value: ${default_display_brightness}

  - id: display_refresh_interval
    type: int
    restore_value: true
    initial_value: ${default_display_refresh_interval}

  - id: wifi_enabled
    type: bool
    restore_value: true
    initial_value: "true"

packages:
  hardware: !include obivan/hardware.yaml
  victronble: !include obivan/victronble.yaml
  lvgl_gui: !include obivan/display/main.yaml
