substitutions:
    device_name: "victronble04"
    friendly_name: "BLE Proxy 04 TFT"
  
  esphome:
    name: ${device_name}
    friendly_name: ${device_name}
    comment: TTGO T4 TFT 2.2" Victron Monitor
  
  external_components:
    - source: github://Fabian-Schmidt/esphome-victron_ble
  
  esp32:
    board: esp32dev
    framework:
      type: esp-idf        # Změna z esp-idf na arduino - stabilnější pro displeje
      version: recommended    
   
  # Enable logging
  logger:
  
  # Enable Home Assistant API
  api:
    encryption:
      key: "MtD8MNPSqjfvJVqRIjkzwrXsP5HFpsoMDH3uDuhA8f4="
  
  ota:
    - platform: esphome
      password: "842c5e28ecee202ad77f0473e1fe199d"
  
  wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password
  
  #time:
  #  - platform: sntp
  #    id: sntp_time
  #    timezone: Europe/Prague
  
  # esp32_ble_tracker:      # DOČASNĚ VYPNUTO PRO DEBUGGING BOOTLOOP
  #   scan_parameters:
  #     interval: 2000ms    # Pomalejší scan pro stabilitu
  #     window: 1000ms      
  #     active: true
  
  # Global variables
  #globals:
  #  - id: current_page
  #    type: int
  #    restore_value: no
  #    initial_value: '0'
  
  # victron_ble: VYPNUTO PRO DEBUGGING BOOTLOOP
  # - id: MySmartShunt
  #   mac_address: "AA:BB:CC:DD:EE:FF"    # PLACEHOLDER
  #   bindkey: "00000000000000000000000000000000"  # PLACEHOLDER
  
  # sensor: VŠECHNY SENSORY VYPNUTY PRO DEBUGGING
  # # === MySmartShunt (Battery Monitor) ===
  # - platform: victron_ble
  #   victron_ble_id: MySmartShunt
  #   name: "Shunt Battery Voltage"
  #   type: BATTERY_VOLTAGE
  #   id: shunt_battery_voltage
  # VŠECHNY SENSORY VYPNUTY PRO DEBUGGING BOOTLOOP
  
  # Všechny sensory a tlačítka vypnuty pro debugging bootloop
  
  # text_sensor: VYPNUTO PRO DEBUGGING
  # # === MySmartSolar (MPPT Solar Charger) ===
  # - platform: victron_ble
  #   victron_ble_id: MySmartSolar
  #   name: "MPPT Device State"
  #   type: DEVICE_STATE
  #   id: mppt_device_state
  
  # Fonts pro TFT displej - ZJEDNODUŠENO PRO DEBUGGING
  font:
    - file: "Roboto-Bold.ttf"
      id: roboto_big
      size: 28  # Titulek a hlavní hodnoty (velký, dobře čitelný)
    - file: "Roboto-Bold.ttf"
      id: roboto
      size: 16  # Sekce/sloupce
    - file: "Roboto-Thin.ttf"
      id: roboto_sm
      size: 13  # Popisky, doplňkové hodnoty/menší text
    - file: "materialdesignicons-webfont.ttf"
      id: mdi
      size: 18  # Ikony - optimální velikost pro sekce
      glyphs: [
        "\U000F0079", # mdi-battery
        "\U000F0590", # mdi-solar-panel  
        "\U000F1012", # mdi-transmission-tower
        "\U000F140A", # mdi-lightning-bolt
        "\U000F0238", # mdi-gauge
        "\U000F0425", # mdi-power-plug
        "\U000F06E8", # mdi-flash
        "\U000F0A02", # mdi-sine-wave
        ]
    - file: "materialdesignicons-webfont.ttf"
      id: mdi_small
      size: 14  # Status ikony - optimální pro inverse boxes
      glyphs: [
        # Connection status ikony
        "\U000F0079", # mdi-battery (SmartShunt)
        "\U000F007A", # mdi-battery-outline (SmartShunt offline)
  
        "\U000F1A74", # mdi-solar-panel (MPPT)
        "\U000F010B", # mdi-car (OrionXS)
        "\U000F010C", # mdi-car-battery (OrionXS)
  
  
        ] 
  
  # === BACKLIGHT CONTROL - DOČASNĚ VYPNUTO PRO DEBUGGING ===
  # output:
  #   - platform: ledc
  #     pin: GPIO4  # GPIO4 může způsobovat boot problémy
  #     id: backlight_pwm
  # 
  # light:
  #   - platform: monochromatic
  #     output: backlight_pwm
  #     name: "Display Backlight"
  #     id: backlight
  #     restore_mode: ALWAYS_ON
  #     default_transition_length: 250ms
  
  # SPI konfigurace - boot-safe piny
  spi:
    clk_pin: GPIO14   # Boot-safe CLK pin
    mosi_pin: GPIO13  # Boot-safe MOSI pin
    # miso_pin nepotřebujeme pro displej
  
  # TFT Display konfigurace podle tvé desky
  display:
    - platform: ili9xxx
      model: ili9341
      cs_pin: GPIO15    # Boot-safe CS pin  
      dc_pin: GPIO2     # Boot-safe DC pin
      reset_pin: GPIO16 # Boot-safe reset pin
      rotation: 270   # Landscape orientace (320x240)
      invert_colors: false  # Povinný parametr pro ili9xxx
      id: tft_display
      #update_interval: 10s  # Velmi pomalá aktualizace pro debugging
      
      lambda: |-
        // MINIMÁLNÍ TEST DISPLEJE PRO DEBUGGING BOOTLOOP
        it.fill(Color(0, 0, 0));  // Černá obrazovka
        it.printf(160, 120, id(roboto_big), Color(255, 255, 255), TextAlign::CENTER, "ESP32 OK");
        it.printf(160, 140, id(roboto_sm), Color(255, 255, 255), TextAlign::CENTER, "Display test");
  
  
      