# =========================================
# NETWORK CONFIGURATION
# WiFi, Time, OTA, and Network Services
# =========================================

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

    - ssid: !secret wifi2_ssid
      password: !secret wifi2_password

  # Diagnostické nastavení pro řešení Auth Expired problému
  power_save_mode: LIGHT # Vypnuto pro diagnostiku
  passive_scan: true # Aktivní scan pro lepší detekci
  #fast_connect: false # Pomalejší ale spolehlivější připojení
  output_power: 17dB # Maximální vysílací výkon

  # Explicitní autentifikační metoda
  #auth_mode: WPA2_PSK

  #manual_ip:
  #  static_ip: 192.168.4.26
  #  gateway: 192.168.4.1
  #  subnet: 255.255.252.0
  #output_power: 17dB

  # Synchronizace RTC při připojení WiFi
  # SNTP automaticky synchronizuje při připojení, RTC se aktualizuje v on_time_sync callbacku
  on_connect:
    then:
      - logger.log: "WiFi connected - SNTP will synchronize RTC time automatically"
      - delay: 5s  # Počkat na stabilizaci WiFi připojení a SNTP synchronizaci
      - lambda: |-
          // SNTP automaticky synchronizuje při připojení WiFi
          // RTC se aktualizuje v on_time_sync callbacku SNTP (řádek 64-75)
          ESP_LOGI("rtc", "WiFi connected - SNTP sync will update RTC automatically");
      # Aktualizuj čas na displeji po synchronizaci (pokud je script dostupný)
      - delay: 2s  # Počkat na dokončení SNTP synchronizace
      - script.execute: update_datetime

# MDNS Discovery (disabled for power saving)
mdns:
  disabled: true

# Time Configuration - Primární RTC, sekundární SNTP synchronizace
# DS3231 RTC je primární zdroj času (funguje i bez WiFi)
# SNTP synchronizuje RTC když je WiFi dostupné
time:
  # Primární zdroj: DS3231 RTC hodiny (LaskaKit DS3231, I2C adresa 0x68)
  - platform: ds1307
    id: rtc_time
    i2c_id: bus_a
    timezone: Europe/Prague
    on_time_sync:
      then:
        - logger.log: "RTC time synchronized"
  
  # Sekundární zdroj: SNTP pro synchronizaci RTC (když je WiFi dostupné)
  - platform: sntp
    id: sntp_time
    timezone: Europe/Prague
    servers:
      - "pool.ntp.org"
      - "time.nist.gov"
      - "0.pool.ntp.org"
    on_time_sync:
      then:
        - logger.log: "SNTP time synchronized - updating RTC"
        - ds1307.write_time:
            id: rtc_time
        - lambda: |-
            // Zapiš log o aktualizaci RTC (čas je už zapsán akcí ds1307.write_time)
            auto rtc_time_now = id(rtc_time).now();
            if (rtc_time_now.is_valid()) {
              ESP_LOGI("rtc", "RTC updated from SNTP: %04d-%02d-%02d %02d:%02d:%02d",
                       rtc_time_now.year, rtc_time_now.month, rtc_time_now.day_of_month,
                       rtc_time_now.hour, rtc_time_now.minute, rtc_time_now.second);
            }

# homeassistant API
api:
  encryption:
    key: "MtD8MNPSqjfvJVqRIjkzwrXsP5HFpsoMDH3uDuhA8f4="

# Over-The-Air Updates
ota:
  - platform: esphome
    password: !secret ota_password

# POZNÁMKA: Synchronizace RTC probíhá automaticky při připojení WiFi
# SNTP komponenta má on_time_sync callback, který zapisuje čas do RTC
# Není potřeba periodický interval - synchronizace proběhne hned při WiFi připojení

# WiFi Signal Strength Sensor
sensor:
  - platform: wifi_signal
    id: wifi_rssi
    name: "WiFi Signal"
    update_interval: 120s # Reduced frequency for power saving
    filters:
      - lambda: |-
          if (!id(wifi_enabled)) {
            return {}; // Don't update when WiFi is disabled
          }
          if (id(aggressive_power_saving)) {
            return {}; // Don't update during screen-off mode for power saving
          }
          return x;
