# =========================================
# HARDWARE CONFIGURATION
# ESP32-S3 Hardware Definitions Only
# =========================================

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 8MB
  cpu_frequency: 240MHz # Keep original for stability with 120MHz PSRAM
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: true
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: "y"
      CONFIG_FREERTOS_HZ: "1000"
      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240: y

      CONFIG_ESPTOOLPY_FLASHMODE_QIO: y
      CONFIG_ESPTOOLPY_FLASHFREQ_120M: y
      CONFIG_SPIRAM_MODE_OCT: y
      CONFIG_IDF_EXPERIMENTAL_FEATURES: y
      CONFIG_SPIRAM_SPEED_120M: y
      CONFIG_PM_ENABLE: y
      CONFIG_FREERTOS_USE_TICKLESS_IDLE: y
      CONFIG_PM_DFS_INIT_AUTO: y
      CONFIG_PM_PROFILING: y
      # WiFi power save enhancements
      CONFIG_ESP_WIFI_PS_MAX_MODEM: y
      CONFIG_ESP_WIFI_PS_MODEM: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
      CONFIG_COMPILER_OPTIMIZATION_PERF: y

esphome:
  name: obivan-s7
  friendly_name: ObiVan-S7
  min_version: "2025.4.2"
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: dio
    board_upload.maximum_ram_size: 524288

  on_boot:
    # Early WiFi control based on saved wifi_enabled state (after NVS restore)
    - priority: 200 # After globals restore, before normal boot
      then:
        - lambda: |-
            ESP_LOGI("boot", "=== EARLY WIFI CONTROL DEBUG ===");
            ESP_LOGI("boot", "Priority 200: Globals should be restored from NVS now");
            ESP_LOGI("boot", "wifi_enabled current value: %s", id(wifi_enabled) ? "TRUE" : "FALSE");
            ESP_LOGI("boot", "wifi_enabled initial_value in config: TRUE");
            ESP_LOGI("boot", "If current != initial, then NVS was successfully loaded");

            if (!id(wifi_enabled)) {
              ESP_LOGI("boot", "DECISION: WiFi was disabled in previous session - disabling immediately");
              ESP_LOGI("boot", "This should prevent connection attempts during boot");
            } else {
              ESP_LOGI("boot", "DECISION: WiFi was enabled in previous session - allowing auto-start");
              ESP_LOGI("boot", "Normal WiFi boot sequence will proceed");
            }
            ESP_LOGI("boot", "=== END EARLY WIFI CONTROL DEBUG ===");
        - if:
            condition:
              lambda: "return !id(wifi_enabled);"
            then:
              - wifi.disable:
              - logger.log: "WiFi disabled early in boot sequence - preventing connection attempts"

    - priority: 600 # Po hardware init
      then:
        # Spustit boot timeout parallel s boot sekvencí
        - script.execute: boot_with_timeout

    - priority: -10
      then:
        - script.execute: boot_with_timeout
        - logger.log: "System initialized with saved brightness and services restored"

# External PSRAM Configuration
psram:
  mode: octal
  speed: 120MHz # Restored from 80MHz to maintain stability

# I2C Bus Configuration
i2c:
  sda: GPIO08
  scl: GPIO09
  scan: true
  id: bus_a

# Backlight
# GPIO16 is mapped to RS-485 output port, pin A
# This GPIO should be wired to the solderpad on the right of the ESP32-S3 module, next to its antenna, below 2 * 0603 ceramic capacitors
# https://community.home-assistant.io/t/esp32-s3-7inch-capacitive-touch-display-adjust-brightness/771030
output:
  - platform: ledc
    pin: GPIO16
    id: id_output_backlight_brightness
    min_power: 0.08
    frequency: 5000Hz

# NOVÉ - Light komponenta pro brightness control:
light:
  - platform: monochromatic
    output: id_output_backlight_brightness
    name: "Display Brightness"
    id: display_backlight_control
    restore_mode: RESTORE_DEFAULT_ON
    default_transition_length: 250ms

ch422g:
  - id: ch422g_hub
    # Konfigurace pro low-power režim
    i2c_id: bus_a

switch:
  - platform: restart
    name: "Restart"
    id: device_restart

  #  - platform: safe_mode
  #    name: Use Safe Mode
  #    id: device_safe_mode

  - platform: gpio
    id: lcdbacklight
    name: lcdbacklight
    pin:
      ch422g: ch422g_hub
      number: 2
      mode:
        output: true
      inverted: false
    restore_mode: ALWAYS_ON

# Touch screen
touchscreen:
  platform: gt911
  address: 0x5D
  id: my_touchscreen
  interrupt_pin: 4
  reset_pin:
    ch422g: ch422g_hub
    number: 1
  on_release:
    - if:
        condition:
          and:
            - switch.is_off: lcdbacklight
            - light.is_off: display_backlight_control
            - lambda: "return !id(ignore_touch);"
        then:
          - logger.log: "Touch detected - waking up screen"
          - script.execute: screen_on_mode
          - globals.set:
              id: manual_display_off
              value: "false"
          - logger.log: "Screen activated by touch"

# Display
display:
  - platform: rpi_dpi_rgb
    id: device_display
    update_interval: never
    auto_clear_enabled: false
    color_order: RGB
    pclk_frequency: 16MHz
    dimensions:
      width: 800
      height: 480
    reset_pin:
      ch422g: ch422g_hub
      number: 3
    de_pin:
      number: 5
    hsync_pin:
      number: 46
      ignore_strapping_warning: true
    vsync_pin:
      number: 3
      ignore_strapping_warning: true
    pclk_pin: 7
    pclk_inverted: true
    hsync_back_porch: 8
    hsync_front_porch: 8
    hsync_pulse_width: 4
    vsync_back_porch: 16
    vsync_front_porch: 16
    vsync_pulse_width: 4
    data_pins:
      red:
        - 1 #r3.
        - 2 #r4.
        - 42 #r5
        - 41 #r6
        - 40 #r7
      blue:
        - 14 #b3
        - 38 #b4
        - 18 #b5
        - 17 #b6
        - 10 #b7
      green:
        - 39 #g2
        - 0 #g3.
        - 45 #g4
        - 48 #g5
        - 47 #g6
        - 21 #g7

# Include Core Components
packages:
  network: !include core/network.yaml
  system: !include core/system.yaml
  power: !include core/power.yaml
  # lvgl_gui: !include display/main.yaml
